### ISSUE TITLE
Zoom continues upon rotate

### ISSUE THREAD

**Issue by OliverEvans96** [maartenbreddels/ipyvolume#29] opened 2017-06-08 23:09 UTC
1. Zoom in or out
2. Rotate

Zooming continues automatically in the same direction upon rotation, which can be confusing. Any idea why this might be occurring?

Oliver

**Comment by maartenbreddels** [comment] 2017-06-09 08:44
It's annoying. It is enabled here by default:
https://github.com/maartenbreddels/ipyvolume/blob/2ea543dd600eeaf899487d30633182b6ad04cf08/js/src/three/TrackballControls.js#L30
The expected behaviour for TrackballControls is a continuous update loop, so running at max fps. But that wastes cpu cycles, so I've hacked this control a bit, but this part is not working correctly, maybe changing these parameters simply fixes it.

**Comment by OliverEvans96** [comment] 2017-06-14 23:37
Where did you do this hacking? It looks like you only have an initial commit and a one-line change for TrackballControlls.js.

**Comment by OliverEvans96** [comment] 2017-06-15 15:34
Basically, it seems like the update loop stops when the click event ends, but the dynamic damping effect continues for a short period after, but is paused until the event loop starts up again (triggered by rotation/zooming). If you point me in the right direction, I think it should be straightforward to stop the event loop when the damped motion is finished.

**Comment by maartenbreddels** [comment] 2017-06-15 18:17
It could be that in the end there wasn't much change to make it work, so that single line was enough :).

I see two options:
 * change staticMoving to true, no smooth animation.
 * check at the end of FigureView.update if we have camera_control equals 'trackball;, and if control_trackball._lastAngle > epsilon (where epsilon is small, say 0.01 or 0.001), if so, call this.update(), so that the animation is continued.

Feel free to try and let me know what you think is best. My preference goes to the first, since it is simpler and more similar I think to the orbit control, and will use less cpu cycles.

**Comment by maartenbreddels** [comment] 2017-08-22 20:19
This is fixed in d2c302a76a8a37087e95352b6a4688943f44982a the trick was setting dampingFactor to 1. And I've made the cameras behave a bit more similar, the old behaviour caused a jump after scrolling.

**Closed by maartenbreddels** 2017-08-22 20:19 UTC
