### ISSUE TITLE
Running ipyvolume in Pycharm

### ISSUE THREAD

**Issue by jbehura** [maartenbreddels/ipyvolume#211] opened 2018-11-27 18:01 UTC
Hi,

I was wondering if one can use ipyvolume outside of Jupyter notebooks.

Cheers,
Jyoti

**Comment by maartenbreddels** [comment] 2018-11-29 11:40
No, not currently, although it might be possible inside VScode (if they add support for widgets).
Anyway, duplicate of #204

**Closed by maartenbreddels** 2018-11-29 11:40 UTC
